version: 1.0.{build}

before_build:
  - git clone --depth 1 https://github.com/mupen64plus/mupen64plus-win32-deps.git ..\mupen64plus-win32-deps
  - git clone --depth 1 https://github.com/mupen64plus/mupen64plus-core.git ..\mupen64plus-core

build_script:
  - msbuild projects\msvc\mupen64plus-input-sdl.vcxproj /p:Configuration=Release;Platform=x64
  - msbuild projects\msvc\mupen64plus-input-sdl.vcxproj /p:Configuration=Release;Platform=Win32

after_build:
  - ps: $env:rev = git describe --tags
  - md tdata_x64 tdata_x86
  - cd tdata_x64
  - copy ..\projects\msvc\x64\Release\*.dll .
  - copy ..\data\* .
  - 7z a -t7z "..\build\mupen64plus-input-sdl_v%rev%_x64.7z" *
  - cd ..\tdata_x86
  - copy ..\projects\msvc\Win32\Release\*.dll .
  - copy ..\data\* .
  - 7z a -t7z "..\build\mupen64plus-input-sdl_v%rev%_x86.7z" *

artifacts:
  - path: build\*.7z
    name: Input SDL
